Repository Clinical-Genomics/BALSAMIC, pull requests merged in 2021-08, with the labels that each got.

#698 Fix/delly run
  BALSAMIC/config/analysis.json
  BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
  BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule
  BALSAMIC/utils/models.py
  BALSAMIC/workflows/balsamic.smk
  CHANGELOG.rst
Labels: Effort Medium, Gain Large, Urgency Medium

#699 Add ascat tumor normal rule
  BALSAMIC/config/analysis.json
  BALSAMIC/config/cluster.json
  BALSAMIC/containers/ascatngs/__init__.py
  BALSAMIC/containers/ascatngs/ascatngs.yaml
  BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
  BALSAMIC/utils/constants.py
  BALSAMIC/utils/models.py
  BALSAMIC/workflows/balsamic.smk
  CHANGELOG.rst
Labels: Gain Large, Urgency Large, Effort Large

#706 Fix/All containers´ performance improvements and fix for varcall_py36 container build
  .github/workflows/docker_build_test_pull_request.yml
  .github/workflows/docker_build_test_submodules.yml
  BALSAMIC/containers/align_qc/align_qc.yaml
  BALSAMIC/containers/annotate/annotate.yaml
  BALSAMIC/containers/ascatngs/ascatngs.yaml
  BALSAMIC/containers/coverage_qc/coverage_qc.yaml
  BALSAMIC/containers/varcall_cnvkit/varcall_cnvkit.yaml
  BALSAMIC/containers/varcall_delly/varcall_delly.yaml
  BALSAMIC/containers/varcall_py27/varcall_py27.yaml
  BALSAMIC/containers/varcall_py36/varcall_py36.yaml
  BALSAMIC/utils/cli.py
  CHANGELOG.rst
Labels: Bug, Gain Large, Urgency Large, Effort Large

#710 Feat/manta convert inversions
  BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_normal.rule
  BALSAMIC/snakemake_rules/variant_calling/somatic_sv_tumor_only.rule
  CHANGELOG.rst
Labels: Gain Large, Urgency Large, Effort Small

#714 Refactor/params to constants
  BALSAMIC/snakemake_rules/align/bwa_mem.rule
  BALSAMIC/snakemake_rules/align/sentieon_alignment.rule
  BALSAMIC/snakemake_rules/annotation/vep.rule
  BALSAMIC/snakemake_rules/umi/mergetype_normal_umi.rule
  BALSAMIC/snakemake_rules/umi/mergetype_tumor_umi.rule
  BALSAMIC/snakemake_rules/umi/sentieon_consensuscall.rule
  BALSAMIC/snakemake_rules/umi/sentieon_umiextract.rule
  BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope.rule
  BALSAMIC/snakemake_rules/umi/sentieon_varcall_tnscope_tn.rule
  BALSAMIC/snakemake_rules/variant_calling/cnvkit_paired.rule
  BALSAMIC/snakemake_rules/variant_calling/cnvkit_single.rule
  BALSAMIC/snakemake_rules/variant_calling/mergetype_normal.rule
  BALSAMIC/snakemake_rules/variant_calling/mergetype_tumor.rule
  BALSAMIC/snakemake_rules/variant_calling/sentieon_germline.rule
  BALSAMIC/snakemake_rules/variant_calling/sentieon_t_varcall.rule
  BALSAMIC/snakemake_rules/variant_calling/sentieon_tn_varcall.rule
  BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_normal.rule
  BALSAMIC/snakemake_rules/variant_calling/somatic_tumor_only.rule
  BALSAMIC/utils/constants.py
  BALSAMIC/utils/models.py
  BALSAMIC/workflows/PON.smk
  BALSAMIC/workflows/UMIworkflow.smk
  BALSAMIC/workflows/balsamic.smk
  CHANGELOG.rst
  tests/utils/test_models.py
Labels: Refactor

#733 feat: ascatngs hg38 references
  BALSAMIC/utils/constants.py
  CHANGELOG.rst
Labels: Effort Medium, Urgency Small, Gain Small
